.Dd 28/03/2025
.Dt swift-package-override 1
.Os NordVPN

.Sh NAME

.Nm swift-package-override
.Nd perform Swift package dependency version overrides

.Sh SYNOPSIS

.Nm

.Sh DESCRIPTION

.Nm
is a tool to assist with performing ad-hoc Swift package dependency version overrides against Swift packages and Xcode projects.

For usage information, see:
.Cm swift-package-override help
