#!/bin/bash
# Contact: Tim Sheridan <tim.sheridan@nordsec.com>

set -eu

TRUE=1
FALSE=0

EX_OK=0
EX_USAGE=1
EX_NOTFOUND=2
EX_DATAERR=3
EX_SOFTWARE=4

SWIFTPM_OVERRIDE_CONFIG_DIR=".swiftpm_override"
SWIFTPM_OVERRIDE_CONFIG_FILE="$SWIFTPM_OVERRIDE_CONFIG_DIR/config"
SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE="$SWIFTPM_OVERRIDE_CONFIG_DIR/manifest"
SWIFT_PACKAGE_OVERRIDE_PROJECTS="$SWIFTPM_OVERRIDE_CONFIG_DIR/projects"

_validate_swift_package() {
	local DIR="$1"; shift

	_xcode_select

	cd "$DIR"
	swift package describe > /dev/null || {
		echo "Error: failed to detect Swift package in `realpath $DIR`" >&2
		exit $EX_NOTFOUND
	}
	cd - > /dev/null
}

_pbx_util_gen_id() {
	python3 - << EOF
import os
print(str(os.urandom(12).hex()).upper())
EOF
}

_pbx_util_main_group_id() {
	PBX_FILENAME="$1"; shift

	python3 - "${PBX_FILENAME}" << EOF
import json
import sys

pbxproj_filename = sys.argv[1]

main_group = None

with open(pbxproj_filename) as f:
	json_string = f.read()
	d = json.loads(json_string)
	for key in d['objects']:
		obj = isa = d['objects'][key]
		isa = obj.get('isa')
		if isa  == 'PBXProject':
			main_group = obj['mainGroup']
			print(main_group)
EOF
}

_pbx_import_package() {
	local PBX_FILENAME="$1"; shift
	local PACKAGE_NAME="$1"; shift
	local PACKAGE_PATH="$1"; shift

	local NEW_ID=""

	while [ "$NEW_ID" == "" ]; do
		local POTENTIAL_ID="`_pbx_util_gen_id`"
		/usr/libexec/PlistBuddy -c "print :objects:${POTENTIAL_ID}" "${PBX_FILENAME}" &> /dev/null || {
			# We want a miss
			NEW_ID="$POTENTIAL_ID"
		}
	done

	/usr/libexec/PlistBuddy -c "add :objects:${NEW_ID}:isa string PBXFileReference"      "$PBX_FILENAME"
	/usr/libexec/PlistBuddy -c "add :objects:${NEW_ID}:lastKnownFileType string wrapper" "$PBX_FILENAME"
	/usr/libexec/PlistBuddy -c "add :objects:${NEW_ID}:name string ${PACKAGE_NAME}"      "$PBX_FILENAME"
	/usr/libexec/PlistBuddy -c "add :objects:${NEW_ID}:path string ${PACKAGE_PATH}"      "$PBX_FILENAME"
	/usr/libexec/PlistBuddy -c "add :objects:${NEW_ID}:sourceTree string <group>"        "$PBX_FILENAME"

	cp "$PBX_FILENAME" "$PBX_FILENAME.json"
	plutil -convert json "$PBX_FILENAME.json"
	local MAIN_GROUP_ID=`_pbx_util_main_group_id "$PBX_FILENAME.json"`
	rm "$PBX_FILENAME.json"

	/usr/libexec/PlistBuddy -c "add :objects:${MAIN_GROUP_ID}:children:0 string ${NEW_ID}" "$PBX_FILENAME"
}

_create_package_xcworkspace() {
	local WORKSPACE_NAME="$1"; shift

	mkdir -p "$WORKSPACE_NAME"

	local WORKSPACE_DATA="$WORKSPACE_NAME/contents.xcworkspacedata"

	rm -f "$WORKSPACE_DATA"
	touch "$WORKSPACE_DATA"

	cat >> "$WORKSPACE_DATA" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<Workspace version="1.0">
EOF

	while read PACKAGE_NAME PACKAGE_VERSION GIT_REF; do
		echo "<FileRef location = \"group:Packages/${PACKAGE_NAME}\"></FileRef>" >> "$WORKSPACE_DATA"
	done < "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE"

	cat >> "$WORKSPACE_DATA" << EOF
<FileRef location="container:">
</FileRef>
</Workspace>
EOF
}

_workspace_state_check_dependency() {
	local WORKSPACE_STATE_FILENAME="$1"; shift

	cat "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE" | while read PACKAGE_NAME PACKAGE_VERSION GIT_REF; do
		python3 - "$WORKSPACE_STATE_FILENAME" "$PACKAGE_NAME" "$GIT_REF" << EOF
import json
import os
import sys

workspace_state_filename = sys.argv[1]
package_name = sys.argv[2]
git_rev = sys.argv[3]

with open(workspace_state_filename) as f:
	json_string = f.read()
	d = json.loads(json_string)

	for dependency in d['object']['dependencies']:
		if dependency['packageRef']['identity'] == package_name.lower():
			if dependency['state']['name'] == 'edited':
				sys.stdout.write(f'Dependency \"{package_name}\" override verified as edited\n')
				sys.exit(os.EX_OK)
			elif dependency['state']['name'] == 'sourceControlCheckout' and dependency['state']['checkoutState']['revision'] == git_rev:
				sys.stdout.write(f'Dependency \"{package_name}\" override verified as matching git ref\n')
				sys.exit(os.EX_OK)
			else:
				sys.stderr.write(f'Dependency \"{package_name}\" override not found\n')
				sys.exit(os.EX_SOFTWARE)

	sys.stdout.write(f'Dependency \"{package_name}\" override verified as absent dependency\n')
	sys.exit(os.EX_OK)
EOF

	done
}

_xcode_select() {
	local XCODE_VERSION_FILENAME=".xcode-version"

	if [ ! -f "$XCODE_VERSION_FILENAME" ] ; then
		# Classic non-xcodes project behavior
		# FIXME This is a silent error path for a project with this file but deeper than the root
		# Can be fixed when we've added support for discovering the project root for deep execution
		return
	fi

	which xcodes > /dev/null || {
		echo "Error: $XCODE_VERSION_FILENAME file present in project but xcodes command not found" >&2
		exit $EX_SOFTWARE
	}

	local CURRENT_XCODE_VERSION=$(defaults read "`xcode-select -p`/../Info" CFBundleShortVersionString)
	local XCODE_VERSION=`head -n 1 $XCODE_VERSION_FILENAME`

	if [ "$XCODE_VERSION" == "$CURRENT_XCODE_VERSION" ]; then
		# Already selected
		return
	fi

	# Print error in case of missing Xcode version
	xcodes installed $XCODE_VERSION > /dev/null || xcodes installed $XCODE_VERSION >&2

	echo "swift-package-override is switching to Xcode $XCODE_VERSION set in $XCODE_VERSION_FILENAME" >&2
	export DEVELOPER_DIR="$(xcodes installed $XCODE_VERSION)/Contents/Developer"
}

_project_import() {
	if [ ! -f "$SWIFT_PACKAGE_OVERRIDE_PROJECTS" ]; then
		return
	fi

	cut -f 1 -d ' ' "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE" | while read PACKAGE_NAME; do
		echo "" | cat "$SWIFT_PACKAGE_OVERRIDE_PROJECTS" - | while read LINE; do
			if [ "$LINE" == "" ]; then
				continue
			fi

			local PROJECT="$LINE"
			local PBXPROJ_FILE="$PROJECT/project.pbxproj"
			if [ ! -f "$PBXPROJ_FILE" ]; then
				echo "Error: project.pbxproj file not found for project: $PROJECT" >&2
				exit $EX_DATAERR
			fi

			echo "Adding '$PACKAGE_NAME' checkout to project: $PROJECT"
			_pbx_import_package "$PBXPROJ_FILE" "$PACKAGE_NAME" "$PWD/$SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR/Packages/$PACKAGE_NAME"
		done
	done
}

############################

cmd_show() {
	if [ ! -f "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE" ]; then
		echo "No SwiftPM package overrides" >&2
		return
	fi

	echo "SwiftPM package overrides:" >&2
	while read PACKAGE_NAME PACKAGE_VERSION GIT_REF; do
		echo "$PACKAGE_NAME $PACKAGE_VERSION $GIT_REF"
	done < "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE"
}

cmd_set() {
	if [ $# -eq 0 ]; then
		echo "Creating empty manifest" >&2
		mkdir -p "$SWIFTPM_OVERRIDE_CONFIG_DIR"
		touch "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE"
		return
	fi

	while [ $# -gt 0 ]; do
		local PACKAGE_NAME_SPECIFIER="$1"; shift
		local PACKAGE_VERSION="$1"; shift

		local PACKAGE_NAME="${PACKAGE_NAME_SPECIFIER%\?}"

		if [ "${PACKAGE_NAME_SPECIFIER:0-1}" == "?" ]; then
			local PACKAGE_OPTIONAL=$TRUE
		else
			local PACKAGE_OPTIONAL=$FALSE
		fi

		local BASE_DIR=`pwd`

		# Override dependency pre-flight

		grep "^$PACKAGE_NAME\t" "$BASE_DIR/$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE" &> /dev/null && {
			echo "Error: Dependency $PACKAGE_NAME has already been overriden" >&2
			exit $EX_DATAERR
		}

		_validate_swift_package "$SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR"

		# Skip missing optional dependency overrides

		if [ $PACKAGE_OPTIONAL -eq $TRUE ]; then
			pushd "$SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR"
			swift package show-dependencies | grep -i " ${PACKAGE_NAME}<" > /dev/null || {
				echo "Warning: Skipping absent optional package override for dependency: $PACKAGE_NAME" >&2

				# Create manifest file so it's there for verification in case this is the only package override
				touch "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE"

				popd
				continue
			}
			popd
		fi

		# Start dependency override

		pushd $SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR &> /dev/null
		echo "Editing SwiftPM package '$PACKAGE_NAME' to '$PACKAGE_VERSION'"
		swift package edit --revision $PACKAGE_VERSION $PACKAGE_NAME
		if [ ! -d "Packages/${PACKAGE_NAME}" ]; then
			echo "Error: Failed to override package" >&2
			exit $EX_DATAERR
		fi
		pushd "Packages/$PACKAGE_NAME" &> /dev/null
		local GIT_REF=`git rev-parse HEAD`
		popd &> /dev/null
		popd &> /dev/null

		mkdir -p "$SWIFTPM_OVERRIDE_CONFIG_DIR"
		echo "$PACKAGE_NAME $PACKAGE_VERSION $GIT_REF" >> "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE"

		echo "SwiftPM package override applied"
	done

	# Create checkouts symlink

	if [ $SWIFTPM_OVERRIDE_CONFIG__CREATE_CHECKOUTS_SYMLINK -eq 1 ]; then
		echo "Creating symlink for package override: $SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR/.build/checkouts/$PACKAGE_NAME"
		ln -s "../../Packages/$PACKAGE_NAME" "$SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR/.build/checkouts/$PACKAGE_NAME"
	fi

	# Import package overrides into Xcode projects
	if [ $SWIFTPM_OVERRIDE_CONFIG__PROJECT_IMPORT_ON_OVERRIDE -eq 1 ]; then
		_project_import
	fi

	# Generate SwiftPM package xcworkspace

	if [ $SWIFTPM_OVERRIDE_CONFIG__CREATE_PACKAGE_WORKSPACE -eq 1 ]; then
		local XCWORKSPACE_FILENAME="package.xcworkspace"
		echo "Generating SwiftPM package xcworkspace: $XCWORKSPACE_FILENAME"
		_create_package_xcworkspace "$XCWORKSPACE_FILENAME"
	fi
}

_err_env_var_not_configured() {
	if [ "$SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR" == "" ]; then
		echo "Error: To use this command, SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR must be set in .swiftpm_override/config" >&2
		exit $EX_DATAERR
	fi
}

cmd_set_env_var() {
	_err_env_var_not_configured

	set +u
	if [ -z "${!SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR}" ]; then
		echo "Error: Environment variable '$SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR' not set" >&2
		exit $EX_DATAERR
	fi
	set -u

	local SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR_EXPANDED="${!SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR}"
	cmd_set $SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR_EXPANDED
}

cmd_status_env_var() {
	_err_env_var_not_configured

	set +u
	if [ -z "${!SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR}" ]; then
		echo "disabled"
	else
		echo "enabled"
	fi
	set -u
	exit 0
}

cmd_project_import() {
	_project_import
}

cmd_clear() {
	if [ ! -f "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE" ]; then
		# Already done
		exit $EX_OK
	fi

	# TODO XXX
	# Warning: This `clear` command is incomplete and out-of-date.
	# It needs updating to behave correctly for the full set of features
	# and configuration options that are supported in the tool.

	_validate_swift_package "$SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR"

	while read PACKAGE_NAME PACKAGE_VERSION; do
		echo "Unediting SwiftPM package '$PACKAGE_NAME'"
		cd "$SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR"
		swift package unedit "$PACKAGE_NAME"
		cd - > /dev/null
	done < "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE"

	rm "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE"
}

_verification_fail() {
	echo "Verification result: FAIL"
}

_verification_pass() {
	echo "Verification result: PASS"
}

cmd_check() {
	local DERIVEDDATA_SUFFIX="SourcePackages/workspace-state.json"
	local BUILD_SUFFIX="workspace-state.json"

	local DERIVEDDATA_AVAILABLE=$FALSE
	local BUILD_AVAILABLE=$FALSE

	if [ "$SWIFTPM_OVERRIDE_CONFIG__DERIVEDDATA_DIR" != "" ] && [ -f "$SWIFTPM_OVERRIDE_CONFIG__DERIVEDDATA_DIR/$DERIVEDDATA_SUFFIX" ]; then
		DERIVEDDATA_AVAILABLE=$TRUE
	fi

	if [ "$SWIFTPM_OVERRIDE_CONFIG__BUILD_DIR" != "" ] && [ -f "$SWIFTPM_OVERRIDE_CONFIG__BUILD_DIR/$BUILD_SUFFIX" ]; then
		BUILD_AVAILABLE=$TRUE
	fi

	local WORKSPACE_STATE_FILE=""

	if [ $DERIVEDDATA_AVAILABLE -eq $TRUE ] && [ $BUILD_AVAILABLE -eq $TRUE ]; then
		echo "Warning: Mixed 'build' dir and 'DerivedData' availability -- prefer 'DerivedData'" >&2

		if [ "$SWIFTPM_OVERRIDE_CONFIG__BUILD_DIR/$BUILD_SUFFIX" -nt "$SWIFTPM_OVERRIDE_CONFIG__DERIVEDDATA_DIR/$DERIVEDDATA_SUFFIX" ]; then
			echo "Error: 'build' is unexpectedly newer than 'DerivedData'" >&2
			ls -lash "$SWIFTPM_OVERRIDE_CONFIG__DERIVEDDATA_DIR/$DERIVEDDATA_SUFFIX" >&2 || true
			ls -lash "$SWIFTPM_OVERRIDE_CONFIG__BUILD_DIR/$BUILD_SUFFIX"             >&2 || true
			_verification_fail
			exit $EX_DATAERR
		fi

		local WORKSPACE_STATE_FILE="$SWIFTPM_OVERRIDE_CONFIG__DERIVEDDATA_DIR/$DERIVEDDATA_SUFFIX"
	elif [ $DERIVEDDATA_AVAILABLE -eq $TRUE ]; then
		WORKSPACE_STATE_FILE="$SWIFTPM_OVERRIDE_CONFIG__DERIVEDDATA_DIR/$DERIVEDDATA_SUFFIX"
	elif [ $BUILD_AVAILABLE -eq $TRUE ]; then
		WORKSPACE_STATE_FILE="$SWIFTPM_OVERRIDE_CONFIG__BUILD_DIR/$BUILD_SUFFIX"
	else
		if [ ! -f "$SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE" ]; then
			echo "Error: No manifest found" >&2
			echo "Tip: This means package override was not attempted or failed"
			_verification_fail
			exit $EX_DATAERR
		elif [ `wc -l < $SWIFT_PACKAGE_OVERRIDE_MANIFEST_FILE` -eq 0 ]; then
			# There isn't a workspace file, but we still need to support SWIFTPM_OVERRIDE_FORCE_CHECK_FAILURE
			WORKSPACE_STATE_FILE="/dev/null"
			echo "Warning: manifest is empty" >&2
		else
			echo "Error: Unable to determine workspace-state.json file from swiftpm_override config and files present" >&2
			echo "Tip: Check that SWIFTPM_OVERRIDE_CONFIG__DERIVEDDATA_DIR and SWIFTPM_OVERRIDE_CONFIG__BUILD_DIR are configured correctly" >&2
			_verification_fail
			exit $EX_DATAERR
		fi
	fi

	echo "Performing verification using: $WORKSPACE_STATE_FILE" >&2

	_workspace_state_check_dependency "$WORKSPACE_STATE_FILE"

	_verification_pass

	set +u
	if [ "$SWIFTPM_OVERRIDE_FORCE_CHECK_FAILURE" != "" ]; then
		echo "Forcing verification to fail because SWIFTPM_OVERRIDE_FORCE_CHECK_FAILURE is set" >&2
		exit 1
	fi
	set -u
}

############################

# Config load

# Default config
SWIFTPM_OVERRIDE_CONFIG__PACKAGE_DIR="."
SWIFTPM_OVERRIDE_CONFIG__BUILD_DIR=""
SWIFTPM_OVERRIDE_CONFIG__DERIVEDDATA_DIR=""
SWIFTPM_OVERRIDE_CONFIG__CREATE_PACKAGE_WORKSPACE=0
SWIFTPM_OVERRIDE_CONFIG__CREATE_CHECKOUTS_SYMLINK=0
SWIFTPM_OVERRIDE_CONFIG__SET_ENV_VAR=""
SWIFTPM_OVERRIDE_CONFIG__PROJECT_IMPORT_ON_OVERRIDE=1

if [ -f "$SWIFTPM_OVERRIDE_CONFIG_FILE" ]; then
	. "$SWIFTPM_OVERRIDE_CONFIG_FILE"
fi

print_usage() {
	echo "Usage: $0 <command> [command options]"
	echo "Commands:"
	echo "  show            Show dependency overrides"
	echo "  set             Override dependency version"
	echo "  set-env-var     Override dependencies using configured environment variable"
	echo "  status-env-var  Detect whether dependency override is enabled using environment variable"
	echo "  project-import  Import overrides into Xcode project(s) and workspace(s)"
	echo "  clear           Clear dependency overrides"
	echo "  check           Validate dependency overrides"
	echo "  help"
}

if [ $# -lt 1 ]; then
	print_usage >&2
	exit $EX_USAGE
fi

CMD=$1; shift
case $CMD in
	help)           print_usage ;;
	show)           cmd_show "$@" ;;
	set)            cmd_set "$@" ;;
	set-env-var)    cmd_set_env_var "$@" ;;
	status-env-var) cmd_status_env_var ;;
	project-import) cmd_project_import ;;
	check)          cmd_check "$@" ;;
	clear)          cmd_clear "$@" ;;
	*)              print_usage >&2 ; exit $EX_USAGE ;;
esac
